version: 2
jobs:
  build:
    docker:
      - image: alonsodomin/herd-circleci
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - herd-node-{{ checksum "node/package.yaml" }}
            - herd-console-{{ checksum "console/elm.json" }}
      - run:
          name: Resolve/Update Dependencies
          command: make setup
      - run:
          name: Run tests
          command: make test
      - run:
          name: Install executable
          command: make install
      - save_cache:
          name: Node Stack Dependencies
          key: herd-{{ checksum "node/package.yaml" }}
          paths:
            - ".stack-work"
            - "$HOME/.stack"
      - store_artifacts: # upload build artifact for display in CircleCi
          path: ~/.local/bin/herd
destination: herd