version: "1"
network:
  http:
    host: "0.0.0.0"
    port: 8081
  broker:
    host: "0.0.0.0"
    port: 9010
cluster:
  binding:
    host: "0.0.0.0"
    port: 9002
  seed-nodes:
    - host: "localhost"
      port: 9001
    - host: "localhost"
      port: 9002
storage:
  location: "./sandbox/var/db"