name:                herd-protocol
version:             0.1.0.0
github:              "alonsodomin/herd"
license:             GPL-3
author:              "A. Alonso Dominguez"
maintainer:          "alonso.domin@pm.me"
copyright:           "2019 A. Alonso Dominguez"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/herd#readme>

dependencies:
- aeson
- avro
- base >= 4.9 && < 5
- base64-bytestring
- binary
- binary-orphans
- bytestring
- free
- hashable
- mmorph
- monad-logger
- mtl >= 2.2.2 && < 2.3
- nonempty-containers
- lens
- semigroups
- text
- text-binary
- transformers
- transformers-base
- time
- unordered-containers
- yaml

default-extensions:
- DeriveDataTypeable
- DeriveGeneric
- StandaloneDeriving

library:
  source-dirs: src
  dependencies:
  - json-rpc

tests:
  herd-protocol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - herd-protocol
    - hspec
    - QuickCheck
    - quickcheck-instances
