name:                herd-node
version:             0.1.0.0
github:              "alonsodomin/herd"
license:             GPL-3
author:              "A. Alonso Dominguez"
maintainer:          "alonso.domin@pm.me"
copyright:           "2019 A. Alonso Dominguez"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/herd#readme>

dependencies:
- aeson
- avro
- base >= 4.9 && < 5
- base64-bytestring
- binary
- binary-orphans
- bytestring
- free
- hashable
- mmorph
- monad-logger
- mtl >= 2.2.2 && < 2.3
- nonempty-containers
- lens
- random
- semigroups
- stm
- text
- text-binary
- transformers
- transformers-base
- time
- unordered-containers
- uuid
- yaml
# Herd dependencies
- herd-protocol

default-extensions:
- DataKinds
- DeriveDataTypeable
- DeriveGeneric
- LambdaCase
- MultiParamTypeClasses
- StandaloneDeriving
- RecordWildCards
- TypeOperators
- TypeSynonymInstances

library:
  source-dirs: src
  dependencies:
  - conduit-extra
  - directory
  - distributed-process
  - distributed-process-async
  - distributed-process-client-server
  - distributed-process-extras
  - distributed-process-monad-control
  - distributed-process-simplelocalnet
  - distributed-process-supervisor
  - json-rpc
  - optparse-applicative >= 0.14.2 && < 0.15
  - network-transport
  - network-transport-tcp
  - rocksdb-haskell
  - servant
  - servant-server
  - wai
  - wai-cors
  - warp
  exposed-modules:
  - Herd.CLI
  - Herd.Data.SchemaRegistry
  - Herd.Data.SubjectLog
  - Herd.Node

executables:
  herd:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - herd-node    

  herd-node-codegen:
    main:                Main.hs
    source-dirs:         codegen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - elm-bridge
    - herd-node
    - optparse-applicative >= 0.14.2 && < 0.15
    - servant-elm
    - wl-pprint-text

tests:
  herd-node-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - herd-node
    - hspec
    - QuickCheck
    - quickcheck-instances
